### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by tahmid-23**

### CODE REVIEW

**Comment by tachibanayui** [comment]
should be to staging

**Comment by tahmid-23** [comment]
I don't see why, I have already tested it myself and another PR from staging to main would be useless because I wouldn't change much of anything

**Comment by tachibanayui** [comment]
Bro, master is for "Production code" only

**Comment by tahmid-23** [comment]
> Bro, master is for "Production code" only

there is little reason for this to not become production

**Comment by tachibanayui** [comment]
Then do as you wish, I won't try to stop you anymore

**Review by VegetalDev — APPROVED** [review]

**Pull request merged**
